### ISSUE TITLE
Add checkstyle

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/uml-reverse-mapper#25]
Add Checkstyle with Google style to ensure consistent formatting

**Comment by sivasubramanim** [comment]
@iluwatar : Can I work on this? 
Should the build fail if the code does not adhere to the checkstyle configured standards?

**Comment by iluwatar** [comment]
Go ahead @sivasubramanim. Yes, it should fail the build if the code is not formatted correctly.

**Comment by sivasubramanim** [comment]
To implement Checkstyle, we would need only to modify the POM files for the projects to include maven-checkstyle-plugin. Also include the Google checkstyle xml as part of the project resources. 

I am planning to use the latest version of the google checkstyle 8.27.Please find the link to the checkstyle file:
https://github.com/checkstyle/checkstyle/blob/checkstyle-8.27/src/main/resources/google_checks.xml

We would need to modify the google_checks.xml file property <property name="severity" value="warning "/> to <property name="severity" value="error"/>, so that all the violations will be treated as errors and will fail the build during violation. 

I ran the build locally and observed the following:
urm-core project - **1562** Checkstyle violations. most of the violations(more than 1000) are indentation issues.
urm-maven project - **865** Checkstyle violations. most of the violations(more than 400) are indentation issues

@iluwatar : As part of this changelist, do you also want me to fix these errors or are you planning to create a separate ticket for fixing the issues?

Please let me know your thoughts.

**Comment by sivasubramanim** [comment]
@iluwatar : Can you please let me know your thoughts on my previous comment?

**Comment by iluwatar** [comment]
@sivasubramanim the implementation plan looks good to me. After adding the Checkstyle plugin we need to fix the violations. I would prefer to to do it in the same ticket but the other option is fine too.
